development:
  sessions:
    default:
      database: msoa_profiles
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: msoa_profiles_test
      hosts:
        - localhost:27017
