source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongoid'
gem 'rabl'

group :test, :development do
  gem 'pry'
  gem 'racksh'
  gem 'database_cleaner'
  gem 'rack-test', require: 'rack/test'
  gem 'factory_girl'
  gem 'rspec'
end
